site_name: Tim Gordon’s blog

# site_url is required for social cards
# See https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/
site_url: https://timgord.com/

site_description : Tim Gordon’s blog
site_author: Tim Gordon
copyright: Copyright &copy; Tim Gordon

# See: https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
#repo_url: https://github.com/TimGord/TimGord.github.io
#repo_name

nav:
  - Recommended reading:
      # The only way I can get links to blog posts to work is to use the external link.
      # For reasons I don't understand, the local and server slugification produce different results
      # when there are dashes in the item title.

      - On contemporary mortality models for actuarial use : 2024-10/on-contemporary-mortality-models-for-actuarial-use/
      - Lisnoti – a proportional font that works for coding too : 2024-01/lisnoti-a-proportional-font-that-works-for-coding-too/
  - About me: about-me.md
  - Reprint policy: reprint-policy.md
  #- Topics : tags.md

theme:

  name: material

  logo: assets/TimGord-white-disc.svg
  favicon: assets/favicon.svg

  # See https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/#autoloading
  font:
    false

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: custom
      accent: orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to automatic mode

  features:
    - content.code.copy # Copy code blocks
    - content.tabs.link
    - navigation.sections 
    - navigation.instant
    #- navigation.tabs # Top level is treated as menu
    #- navigation.tabs.sticky
    - navigation.tracking
    #- navigation.indexes # Headings can be docs too
    - navigation.expand # Headings on left expand when visit page
    - navigation.footer
    - navigation.top    
    #- header.autohide
    #- toc.integrate # MarkDown headings are on LHS NB Not compatible with navigation.indexes
    - search.suggest
    - search.highlight

  custom_dir: overrides

  # Icons for tags
  #icon:
  #  tag:
  #    mortality: material/chart-bell-curve-cumulative
  #    standards: material/scale-balance
  #    maths: material/sigma
  #    coding: material/code-json
  #    forecasting: material/target
  #    plural: material/parking

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - def_list
  - smarty
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons 
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span # Required for features like line highlighting to work correctly
      pygments_lang_class: true # Required for custom annotation markers to function
  #- pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      #permalink: true # Default heading links *after* title
      permalink: '' # GitHub-style heading links *before* title
      title: Page contents
  - pymdownx.details
  #- pymdownx.snippets

# KATEX *and* MATH_JAX
  - pymdownx.arithmatex:
      generic: true
      # Adding block_tag: 'pre' causes equation numbers to be at far right.
      # Without this they are only slightly to the right of an equation.
      block_tag: 'pre'

plugins:
  # Enable explicitly in case we add other plug ins.
  # See: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/
  - search: 
      lang: en

  # The following makes your email address public
  # See https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-authors
  #- git-authors

  #- tags:
  #    enabled: !ENV [CI, false]
  #    tags_file: tags.md

  - blog :
      archive: false ### Turn this off in 2025? ###
      blog_dir: .
      blog_toc: true
      categories_name: Topics      
      post_date_format: yyyy-MM-dd
      post_url_date_format: yyyy-MM
      post_date_format: yyyy-MM-dd # Heading within posts
      archive_date_format: yyyy # How archive is grouped 
      archive_url_date_format: yyyy
      archive_url_format: "{date}"
      post_excerpt: required # This setting means that posts without excerpt separators raise an error.
      #categories_toc: true
      categories_url_format: "topic/{slug}"
      categories_allowed:
        - Coding
        - Forecasting
        - Mortality/longevity
        - Maths/stats
        - Presentation

  # Social cards
  # As at 2024-01-11, I haven't managed to get this to work :-(
  # See https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/
  # You also need other stuff -- see : https://squidfunk.github.io/mkdocs-material/plugins/requirements/image-processing/
  # I used https://www.msys2.org/ as recommended by Material for MkDocs
  # As at 2024-01-11, I haven't managed to get this to work :-(
  # I get: File "C:\Python310\lib\zipfile.py", line 1334, in _RealGetContents raise BadZipFile("File is not a zip file")
  # This is the same error as: https://github.com/squidfunk/mkdocs-material/discussions/3246
  #- social:
  #  cards_layout_options:
  #    font_family: Noto Sans

extra:
  #generator: false

  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tim-gordon-8b59b180/
      name: Tim on LinkedIn
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/LongevityTim/
      name: Tim on X (fka Twitter)

  tags:
    Mortality: mortality
    Standards: standards
    Maths: maths
    Coding: coding
    Forecasting: forecasting
    Plural: plural

extra_css:
  - stylesheets/extra.css
  - stylesheets/github-permalink-style.css  # GitHub-style heading links *before* title

# KATEX
#  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:

# KATEX
#  - javascripts/katex.js
#  - https://unpkg.com/katex@0/dist/katex.min.js
#  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

# MATH_JAX
  - javascripts/mathjax.js
  # Source: https://docs.mathjax.org/en/latest/web/configuration.html
  # Read this on render choice: https://docs.mathjax.org/en/v2.0-latest/output.html#mathjax-output-formats
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # The following was for IE compatibility
  # See https://docs.mathjax.org/en/latest/web/start.html#browser-compatibility
  # But the original author suggests it is no longer required anyway.
  # See https://x.com/triblondon/status/1761852350224846906
  #- https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6



