site_name: Tim Gord

site_url: https://timgord.com/

nav:
    - Blog :
        - XXX: index.md
        - Measuring concentration: _blog/2023/measuring-concentration.md
    - About :
        - Tim Gordon: _about/tim-gordon.md
        - Licensing / reprint policy: _about/reprint-policy.md
    - Topics : tags.md

theme:

  name: material

  logo: assets/FlashIcon.svg
  favicon: assets/favicon.svg

  # See https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/
  font:
    text: Fira Sans
    code: Fira Code

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.copy # Copy code blocks
    - content.tabs.link
    - navigation.sections 
    - navigation.instant
    - navigation.tabs # Top level is treated as menu
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.indexes # Headings can be docs too
    - navigation.expand # Headings on left expand when visit page
    - navigation.footer
    - navigation.top    
    #- header.autohide
    #- toc.integrate # MarkDown headings are on LHS NB Not compatible with navigation.indexes
    - search.suggest
    - search.highlight

  custom_dir: overrides

  # Icons for tags
  icon:
    tag:
      mortality: material/chart-bell-curve-cumulative
      standards: material/scale-balance
      maths: material/sigma
      coding: material/code-json
      forecasting: material/target
      plural: material/parking

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - def_list
  - smarty
  - pymdownx.tasklist:
      custom_checkbox: true  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      #permalink: true # Default heading links *after* title
      permalink: '' # GitHub-style heading links *before* title
      title: Page contents
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

plugins:
  # Enable explicitly in case we add other plug ins.
  # See: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/
  - search: 
      lang: en
  - tags:
      enabled: !ENV [CI, false]
      tags_file: tags.md

#repo_url: https://github.com/TimGord/TimGord.github.io

site_description : Tim Gordon’s blog
site_author: Tim Gordon
copyright: Copyright &copy; 2023 Tim Gordon

extra:
  #generator: false

  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tim-gordon-8b59b180/
      name: Tim on LinkedIn

  tags:
    Mortality: mortality
    Standards: standards
    Maths: maths
    Coding: coding
    Forecasting: forecasting
    Plural: plural

extra_css:
  - stylesheets/extra.css
  - stylesheets/github-permalink-style.css  # GitHub-style heading links *before* title

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



